services:
    app:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - kindergarten-network

    postgres:
        image: postgres:16-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: isken
            POSTGRES_DB: db
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres -d db" ]
            interval: 5s
            retries: 10
        ports:
            - 5434:5432
        volumes:
            - kindergarten-data:/var/lib/postgresql/data
        networks:
            - kindergarten-network

networks:
    kindergarten-network:
        driver: bridge

volumes:
    kindergarten-data: